name = "doorblue"
main = ".svelte-kit/cloudflare/_worker.js"
compatibility_date = "2026-08-31"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = ".svelte-kit/cloudflare"
binding = "ASSETS"

# Configure production secrets with:
# wrangler secret put TELEGRAM_BOT_TOKEN
# wrangler secret put TELEGRAM_WEBHOOK_SECRET
